import { useState } from "react";
import { NextPage } from 'next';
import Head from 'next/head';
import '@/styles/index.css';

const Home: NextPage = () => {
  const [result, setResult] = useState<string | null>(null);

  const showResult = (text: string) => {
    setResult(`📢 ${text}`);
    
  };

  return (
    <div>{/*ห้ามยุ่ง*/}
      <Head>
        <title>Betashifts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="https://img2.pic.in.th/pic/-317175dc83076367f9.png" />
        <meta property="og:image" content="https://img2.pic.in.th/pic/-317175dc83076367f9.png" />
        {/* fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@100..900&display=swap" rel="stylesheet" />
        {/* fonts */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"></link>
        {/* bootstrap */} {/*ส่วนเมนู*/}
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"></link>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        {/* Font Awesome */}
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css'></link>
      </Head>
      
      <nav className="navbar navbar-expand-lg navbar-light fixed-top">
  <a className="navbar-brand" href="/">Navbar</a>
  <button  
    className="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span className="navbar-toggler-icon"></span>
  </button>
  <div className="collapse navbar-collapse" id="navbarNav">
    <ul className="navbar-nav mr-auto">
      <li className="nav-item active">
        <a className="nav-link" href="/">
          หน้าหลัก <span className="sr-only">(current)</span>
        </a>
      </li>
      <li className="nav-item">
        <a className="nav-link" href="service">
          บริการ
        </a>
      </li>
      <li className="nav-item">
        <a className="nav-link" href="team">
          ทีมงาน
        </a>
      </li>
      <li className="nav-item">
        <a className="nav-link" href="https://www.facebook.com/profile.php?id=100087575394420">
          ติดต่อเรา
        </a>
      </li>
    </ul>
    
    {/* ปรับส่วนนี้ให้ปุ่มทางขวา */}
    <ul className="navbar-nav ml-auto">
      {/* <li className="nav-item">
        <a 
          className="nav-link btn btn-secondary text-black px-3 py-2" 
          href="auth/login" 
          style={{
        borderRadius: "10px",
        backgroundColor: "#e0e0e0",
        border: "none",
        transition: "background-color 0.3s ease",
          }}
          onMouseEnter={(e) => e.currentTarget.style.backgroundColor = "#d6d6d6"}
          onMouseLeave={(e) => e.currentTarget.style.backgroundColor = "#e0e0e0"}
        >
          เข้าสู่ระบบ
        </a>
      </li> */}
      <li className="nav-item">
      <a 
          className="nav-link btn btn-primary text-white px-3 py-2" 
          href="https://www.facebook.com/profile.php?id=100087575394420" 
          style={{
            borderRadius: "10px",
            background: "linear-gradient(90deg, #d08aff, #7ac3ff, #94ffc1)",
            border: "none",
            transition: "opacity 0.3s ease",
                }}
          onMouseEnter={(e) => e.currentTarget.style.opacity = "0.9"}
          onMouseLeave={(e) => e.currentTarget.style.opacity = "1"}
                >
            เริ่มต้นใช้งาน
          </a>
      </li>
    </ul>
  </div>
</nav>
      
      <div className="cole"></div>
     
      <div className="main-content-container" style={{
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginTop: '100px',
        padding: '0 40px',
        maxWidth: '1400px',
        marginLeft: 'auto',
        marginRight: 'auto'
      }}>
        <div style={{
          width: '100%',
          maxWidth: '600px',
          paddingRight: '40px'
        }} className="con">
          <h1 style={{
            fontSize: "60px",
          }}>
            <b>
              <span style={{ color: "#2093ff" }}>B</span>
              <span style={{ color: "#ffb516" }}>e</span>
              <span style={{ color: "#15b300" }}>t</span>
              <span style={{ color: "#a621ff" }}>a</span>
              <span style={{ color: "#ff2a2a" }}>s</span>
              <span style={{ color: "#ff650c" }}>h</span>
              <span style={{ color: "#003ee7" }}>i</span>
              <span style={{ color: "#e520ff" }}>f</span>
              <span style={{ color: "#a621ff" }}>t</span>
              <span style={{ color: "#ffb516" }}>s</span>
            </b>
          </h1>
          <p style={{
             maxWidth: '600px',
             wordWrap: 'break-word',
             textAlign: 'left',
             color: '#6e6e6e',
               fontSize: '17px',
          }}>
            บริการปล่อยเช่าเว็บไซต์เริ่มต้นแค่ 150 บาทดำเนินธุรกิจออนไลน์ โดยผู้เช่าสามารถใช้ฟีเจอร์ต่างๆ
            ที่พัฒนาไว้ เช่น ระบบมินเกม ระบบชำระเงิน ระบบโซเชียล หรือหน้าโปรไฟล์ร้านค้า
            โดยไม่ต้องสร้างเว็บไซต์เอง
          </p>
          <button style={
            {
              margin: "10px",
            }
          } id="bu">ดูบริการของเรา</button>
          <button id="bu">เช่าเว็บเลย</button>
        </div>

        {/* Image Container - Moved to top right on desktop, below content on mobile */}
        <div className="img-container" style={{
          width: '100%',
          maxWidth: '600px',
          position: 'relative',
          overflow: 'hidden',
          marginTop: '40px',
          padding: '20px'
        }}>
          {/* Glow Effect Layers */}
          <div style={{
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
            width: "90%",
            height: "90%",
            borderRadius: "30px",
            background: "linear-gradient(135deg, rgba(255,180,180,0.15) 0%, rgba(255,220,220,0.3) 50%, rgba(255,180,180,0.15) 100%)",
            filter: "blur(30px)",
            zIndex: 0,
            animation: "glowPulse 6s ease-in-out infinite alternate"
          }}></div>
          
          <div style={{
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
            width: "85%",
            height: "85%",
            borderRadius: "25px",
            background: "radial-gradient(circle at center, rgba(255,230,230,0.4) 0%, transparent 70%)",
            filter: "blur(20px)",
            zIndex: 1,
            opacity: 0.7
          }}></div>

          {/* Main Image */}
          <div style={{
            position: "relative",
            zIndex: 2,
            width: "100%",
            borderRadius: "20px",
            overflow: "hidden",
            border: "1px solid rgba(255, 220, 220, 0.6)",
            transform: "perspective(1000px) rotateX(0deg) rotateY(0deg)",
            transition: "transform 0.5s ease, box-shadow 0.5s ease",
            animation: "float 5s ease-in-out infinite"
          }}>
            <img 
              src="https://img5.pic.in.th/file/secure-sv1/-356272d1e7d9cf0a4d.png" 
              alt="Betashifts Preview" 
              style={{ 
                width: "100%",
                height: "auto",
                display: "block",
                borderRadius: "20px",
                transform: "scale(1.01)" // Fix for border-radius overflow
              }} 
            />
          </div>

          {/* Floating Particles */}
          {[...Array(10)].map((_, i) => (
            <div key={i} style={{
              position: "absolute",
              top: `${Math.random() * 100}%`,
              left: `${Math.random() * 100}%`,
              width: `${Math.random() * 6 + 2}px`,
              height: `${Math.random() * 6 + 2}px`,
              borderRadius: "50%",
              background: `rgba(255, ${Math.floor(180 + Math.random() * 60)}, ${Math.floor(180 + Math.random() * 60)}, ${Math.random() * 0.4 + 0.2})`,
              filter: "blur(1px)",
              zIndex: 3,
              animation: `floatParticle ${Math.random() * 10 + 10}s linear infinite`,
              animationDelay: `${Math.random() * 5}s`
            }}></div>
          ))}
        </div>
      </div>

      <center>
        <div style={{
          marginTop: "350px",
        }} className="explain">
          <div className="explain-box">
            <h1>เราคือใคร?</h1>
            <p>เราเป็นกลุ่มคนรุ่นใหม่ที่มีความหลงใหลในเทคโนโลยีและการพัฒนาเว็บแอปพลิเคชัน เราเชื่อในพลังของไอเดียสร้างสรรค์ การออกแบบที่เรียบง่าย และการใช้งานที่ตอบโจทย์ผู้ใช้ เราทำงานด้วยความใส่ใจในรายละเอียด เพื่อสร้างผลงานที่มีคุณภาพและสามารถสร้างประโยชน์ให้กับผู้ใช้งานได้จริง</p>
           
          </div>
        </div>
      </center>

      <style jsx global>{`
        @keyframes glowPulse {
          0% { opacity: 0.6; transform: translate(-50%, -50%) scale(0.98); }
          50% { opacity: 0.9; transform: translate(-50%, -50%) scale(1.03); }
          100% { opacity: 0.6; transform: translate(-50%, -50%) scale(0.98); }
        }
        
        @keyframes float {
          0% { transform: perspective(1000px) rotateX(0deg) rotateY(0deg) translateY(0px); }
          50% { transform: perspective(1000px) rotateX(1deg) rotateY(1deg) translateY(-10px); }
          100% { transform: perspective(1000px) rotateX(0deg) rotateY(0deg) translateY(0px); }
        }
        
        @keyframes floatParticle {
          0% { transform: translateY(0) translateX(0); opacity: 0.2; }
          50% { transform: translateY(-50px) translateX(10px); opacity: 0.7; }
          100% { transform: translateY(-100px) translateX(20px); opacity: 0; }
        }
        
        .img-container:hover div:first-of-type {
          filter: blur(40px) brightness(1.1);
        }
        
        .img-container:hover div:nth-of-type(2) {
          opacity: 0.9;
        }

        /* Responsive styles */
        @media (min-width: 768px) {
          .main-content-container {
            flex-wrap: nowrap;
          }
          .img-container {
            margin-top: 0;
          }
          .con {
            width: 50%;
          }
        }

        @media (max-width: 767px) {
          .main-content-container {
            padding: 0 20px;
          }
          .con {
            padding-right: 0;
          }
          h1 {
            font-size: 40px !important;
          }
        }
      `}</style>
     <div className="choose">
  <div className="choose-box">
    <h1>ทำไมถึงต้องเลือกเรา</h1>
    
    <div className="features-container">
  
      <div className="feature-item">
        <div className="feature-icon">
          <i className="fi fi-rr-shield-check"></i>
        </div>
        <h3>คุณภาพที่เรากล้ารับประกัน</h3>
        <p>ราคัดสรรวัสดุหรือระบบที่มีคุณภาพสูง ผ่านกระบวนการผลิตและตรวจสอบอย่างละเอียดในทุกขั้นตอน เพื่อให้มั่นใจว่าสิ่งที่ลูกค้าได้รับจะเป็นสิ่งที่ดีที่สุด ไม่ว่าจะเป็นสินค้า บริการ หรือซอฟต์แวร์</p>
      </div>

    
      <div className="feature-item">
        <div className="feature-icon">
          <i className="fi fi-rr-heart"></i>
        </div>
        <h3>ใส่ใจในทุกรายละเอียด</h3>
        <p>เราเชื่อว่าความแตกต่างเล็กๆ น้อยๆ สามารถสร้างประสบการณ์ที่ดีกว่าให้กับลูกค้าได้ ดังนั้นเราจึงใส่ใจตั้งแต่การออกแบบ คือสิ่งที่ทำให้แบรนด์ของเราน่าจดจำ</p>
      </div>

    
      <div className="feature-item">
        <div className="feature-icon">
          <i className="fi fi-rr-lock"></i>
        </div>
        <h3>ระบบรักษาความปลอดภัยที่คุณวางใจได้</h3>
        <p>เรามีระบบรักษาความปลอดภัยขั้นสูงที่ออกแบบมาเพื่อปกป้องข้อมูลของคุณที่ได้มาตรฐานสากล พร้อมระบบป้องกันภัยและการสำรองข้อมูลที่เชื่อถือได้ เพื่อให้คุณมั่นใจในความปลอดภัยทุกครั้งที่ใช้บริการ</p>
      </div>

     
      <div className="feature-item">
        <div className="feature-icon">
          <i className="fi fi-rr-bolt"></i>
        </div>
        <h3>บริการรวดเร็ว ทันสมัย และตรงใจ</h3>
        <p>ไม่ว่าคุณจะติดต่อสอบถาม แจ้งปัญหา หรือต้องการคำแนะนำ ทีมงานของเราพร้อมให้บริการอย่างรวดเร็ว เพราะเราเข้าใจว่า “เวลา” ของคุณมีค่า</p>
      </div>

     
      <div className="feature-item">
        <div className="feature-icon">
          <i className="fi fi-rr-usd-circle"></i>
        </div>
        <h3>คุ้มค่าทุกบาทที่จ่าย</h3>
        <p>เรามอบสินค้าและบริการที่คุ้มราคา  ไม่มีการยัดเยียดการขาย เราต้องการให้คุณรู้สึกว่าทุกบาทที่จ่ายไป ได้รับกลับมามากกว่าแค่ “ของ” แต่คือ “ความพอใจ” และ “ประสบการณ์ที่ดี”</p>
      </div>

      
      <div className="feature-item">
        <div className="feature-icon">
          <i className="fi fi-rr-clock"></i>
        </div>
        <h3>บริการตลอด 24 ชั่วโมง</h3>
        <p>เราพร้อมให้บริการและช่วยเหลือด้านเทคนิคตลอด 24 ชั่วโมงทุกวัน ด้วยทีมงานมืออาชีพที่พร้อมตอบคำถามและแก้ไขปัญหาอย่างรวดเร็ว เพื่อให้คุณมั่นใจในบริการของเรา</p>
      </div>
    </div>
  </div>
</div>
<div className="footer">
  <div className="footer-section">
  <h1 style={{
            fontSize: "30px",
          }}>
            <b>
              <span style={{ color: "#2093ff" }}>B</span>
              <span style={{ color: "#ffb516" }}>e</span>
              <span style={{ color: "#15b300" }}>t</span>
              <span style={{ color: "#a621ff" }}>a</span>
              <span style={{ color: "#ff2a2a" }}>s</span>
              <span style={{ color: "#ff650c" }}>h</span>
              <span style={{ color: "#003ee7" }}>i</span>
              <span style={{ color: "#e520ff" }}>f</span>
              <span style={{ color: "#a621ff" }}>t</span>
              <span style={{ color: "#ffb516" }}>s</span>
            </b>
          </h1>
    {/* <div><strong>บริษัท เบต้าชิฟ จำกัด</strong></div> */}
    <div>2JR7+JPJ ตำบล คลองหนึ่ง อำเภอคลองหลวง ปทุมธานี 12120</div>
  </div>

  <div className="footer-section">
    <div><strong>ติดต่อเรา</strong></div>
    <div>Facebook: <a style={{
      color: "black",
      textDecoration: "none",
    }} href="https://www.facebook.com/profile.php?id=100087575394420" >Betashifts</a></div>
    <div>Discord: <a style={{
      color: "black",
      textDecoration: "none",
    }} href="https://discord.gg/HUDn3aYGjc" >discord.gg/HUDn3aYGjc</a></div>
  </div>

  <div className="footer-section services">
    <div><strong>บริการของเรา</strong></div>
    <div><img style={{
      borderRadius: "5px",
    }} src="https://img5.pic.in.th/file/secure-sv1/kawaii77aef6f798f28865.png" alt="" height={30} /> คอร์กี้บริการปล่อยเช่าเว็บ</div>
  </div>
</div>
<hr />
<div className="bottom">
© 2025 Betashifts. All rights reserved.
</div>
    </div>/*ห้ามยุ่ง*/
  );
};

export default Home;