import { useState } from "react";
import { NextPage } from 'next';
import Head from 'next/head';
import '@/styles/service.css';

const Home: NextPage = () => {
  const [result, setResult] = useState<string | null>(null);

  const showResult = (text: string) => {
    setResult(`📢 ${text}`);
    
  };

  return (
    <div>{/*ห้ามยุ่ง*/}
      <Head>
        <title>Betashifts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="https://img2.pic.in.th/pic/-317175dc83076367f9.png" />
        <meta property="og:image" content="https://img2.pic.in.th/pic/-317175dc83076367f9.png" />
        {/* fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@100..900&display=swap" rel="stylesheet" />
        {/* fonts */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"></link>
        {/* bootstrap */} {/*ส่วนเมนู*/}
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"></link>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        {/* Font Awesome */}
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css'></link>
      </Head>
      
      <nav className="navbar navbar-expand-lg navbar-light fixed-top">
  <a className="navbar-brand" href="/">Navbar</a>
  <button  
    className="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span className="navbar-toggler-icon"></span>
  </button>
  <div className="collapse navbar-collapse" id="navbarNav">
    <ul className="navbar-nav mr-auto">
    <li className="nav-item">
        <a className="nav-link" href="/">
          หน้าหลัก <span className="sr-only">(current)</span>
        </a>
      </li>
      <li className="nav-item active">
        <a className="nav-link" href="service">
          บริการ
        </a>
      </li>
      <li className="nav-item">
        <a className="nav-link" href="team">
          ทีมงาน
        </a>
      </li>
      <li className="nav-item">
        <a className="nav-link" href="https://www.facebook.com/profile.php?id=100087575394420">
          ติดต่อเรา
        </a>
      </li>
    </ul>
    
    {/* ปรับส่วนนี้ให้ปุ่มทางขวา */}
    <ul className="navbar-nav ml-auto">
      {/* <li className="nav-item">
        <a 
          className="nav-link btn btn-secondary text-black px-3 py-2" 
          href="auth/login" 
          style={{
        borderRadius: "10px",
        backgroundColor: "#e0e0e0",
        border: "none",
        transition: "background-color 0.3s ease",
          }}
          onMouseEnter={(e) => e.currentTarget.style.backgroundColor = "#d6d6d6"}
          onMouseLeave={(e) => e.currentTarget.style.backgroundColor = "#e0e0e0"}
        >
          เข้าสู่ระบบ
        </a>
      </li> */}
      <li className="nav-item">
      <a 
          className="nav-link btn btn-primary text-white px-3 py-2" 
          href="https://www.facebook.com/profile.php?id=100087575394420" 
          style={{
            borderRadius: "10px",
            background: "linear-gradient(90deg, #d08aff, #7ac3ff, #94ffc1)",
            border: "none",
            transition: "opacity 0.3s ease",
                }}
          onMouseEnter={(e) => e.currentTarget.style.opacity = "0.9"}
          onMouseLeave={(e) => e.currentTarget.style.opacity = "1"}
                >
            เริ่มต้นใช้งาน
          </a>
      </li>
    </ul>
  </div>
</nav>
      <div className="ma">
        <p style={
            {
                display: 'flex',
                flexDirection: 'row',
                flexWrap: 'wrap',
                justifyContent: 'space-between',
                alignItems: 'flex-start',
                marginTop: '160px',
                padding: '0 40px',
                maxWidth: '1300px',
                marginLeft: 'auto',
                marginRight: 'auto',
                fontSize: '40px',
                color: '#2d3748',
                fontWeight: 'bold',
            }
        }>บริการดีเข้าใจลูกค้า</p>
      </div>
      <div style={{
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginTop: '20px',
        padding: '0 40px',
        maxWidth: '1300px',
        marginLeft: 'auto',
        marginRight: 'auto',
      }} className="message">
        <p style={{
          maxWidth: '600px',
          textAlign: 'left',
          color: '#6e6e6e',
          fontSize: '18px',
        }}>
          เรานำเสนอหลากหลายบริการที่ออกแบบมาเพื่อตอบโจทย์ทุกความต้องการของลูกค้า
          โดยเน้นคุณภาพ ความรวดเร็ว และความพึงพอใจสูงสุด 
          เพื่อให้คุณได้รับประสบการณ์ที่ดีที่สุดจากเรา
        </p>
      </div>

      <div className="choose">
  <div className="choose-box">
    <div className="features-container">
  
      <div className="feature-item">
        <div className="feature-icon">
        <i className="bi bi-clouds"></i>
        </div>
        <h3>Wed Hosting</h3>
        <p style={{
            maxWidth: '600px',
            wordWrap: 'break-word',
            textAlign: 'left',
            color: '#6e6e6e',
            fontWeight: 'bold',
            
        }}>เริ่มต้นเพียง</p>
        <div  className="pricing-price">700 บาท / ปี</div>
        <center> <button style={{
                    backgroundColor: 'white',
                    color: '#474747',
                    border: '1px solid #d3d3d3',
                    padding: '7px 20px',
                    borderRadius: '7px',
                    fontSize: '16px',
                    marginTop: '10px',
                    width: '100%',
                    maxWidth: '300px',
                    boxSizing: 'border-box',
                    }}>สั่งซื้อ</button>     </center>
        <p style={{
            marginTop: '10px',
        }}>สิ่งที่คุณได้</p>
        <ul style={{ paddingLeft: '20px', marginTop: '10px' }}>
            <li>พื้นที่เก็บข้อมูล SSD ความเร็วสูง</li>
            <li>รองรับการใช้งาน HTTPS</li>
            <li>ระบบสำรองข้อมูลอัตโนมัติ</li>
            <li>การสนับสนุนตลอด 24 ชั่วโมง</li>
            <li>แผงควบคุมใช้งานง่าย</li>
            <li>รองรับหลายโดเมน</li>
        </ul>
      </div>

    
      <div className="feature-item">
        <div className="feature-icon">
        <i className="bi bi-braces"></i>
        </div>
        <h3>บริการปล่อยเช่าเว็บไซต์</h3>
        <p style={{
            maxWidth: '600px',
            wordWrap: 'break-word',
            textAlign: 'left',
            color: '#6e6e6e',
            fontWeight: 'bold',
            
        }}>เริ่มต้นเพียง</p>
        <div  className="pricing-price">99 บาท / เดือน</div>
        <center> <button style={{
                    backgroundColor: 'white',
                    color: '#474747',
                    border: '1px solid #d3d3d3',
                    padding: '7px 20px',
                    borderRadius: '7px',
                    fontSize: '16px',
                    marginTop: '10px',
                    width: '100%',
                    maxWidth: '300px',
                    boxSizing: 'border-box',
                    }}>สั่งซื้อ</button>     </center>
        <p style={{
            marginTop: '10px',
        }}>สิ่งที่คุณได้</p>
        <ul style={{ paddingLeft: '20px', marginTop: '10px' }}>
          <li>UI ที่สวยใช้งานง่าย</li>
          <li>เว็บทันสมัยน่าใช้</li>
          <li>ระบบเติมเงินอัตโนมัติ</li>
          <li>ระบบมินิเกม</li>
          <li>ผสมระหว่างเว็บขายของกับโซเซียลมีเดีย</li>
          <li>ระบบโซเชียล</li>
        </ul>
      </div>
    
      <div className="feature-item">
        <div className="feature-icon">
        <i className="fi fi-rr-hammer"></i>
        </div>
        <h3>บริการรับทำเว็บไซต์</h3>
        <p style={{
            maxWidth: '600px',
            wordWrap: 'break-word',
            textAlign: 'left',
            color: '#6e6e6e',
            fontWeight: 'bold',
            
        }}>เริ่มต้นเพียง</p>
        <div  className="pricing-price">20,000 บาท</div>
        <center> <button style={{
                    backgroundColor: 'white',
                    color: '#474747',
                    border: '1px solid #d3d3d3',
                    padding: '7px 20px',
                    borderRadius: '7px',
                    fontSize: '16px',
                    marginTop: '10px',
                    width: '100%',
                    maxWidth: '300px',
                    boxSizing: 'border-box',
                    }}>สั่งซื้อ</button>     </center>
        <p style={{
            marginTop: '10px',
        }}>สิ่งที่คุณได้</p>
        <ul style={{ paddingLeft: '20px', marginTop: '10px' }}>
            <li>ออกแบบเว็บไซต์ให้ตรงตามความต้องการ</li>
            <li>รองรับการใช้งานบนทุกอุปกรณ์ (Responsive Design)</li>
            <li>เพิ่มฟีเจอร์เฉพาะที่เหมาะสมกับธุรกิจของคุณ</li>
            <li>ปรับแต่ง UI/UX ให้ใช้งานง่ายและทันสมัย</li>
            <li>รองรับ SEO เพื่อเพิ่มโอกาสในการค้นหา</li>
            <li>บริการหลังการขายและการดูแลเว็บไซต์</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<hr />
<div className="footer">
  <div className="footer-section">
  <h1 style={{
            fontSize: "30px",
          }}>
            <b>
              <span style={{ color: "#2093ff" }}>B</span>
              <span style={{ color: "#ffb516" }}>e</span>
              <span style={{ color: "#15b300" }}>t</span>
              <span style={{ color: "#a621ff" }}>a</span>
              <span style={{ color: "#ff2a2a" }}>s</span>
              <span style={{ color: "#ff650c" }}>h</span>
              <span style={{ color: "#003ee7" }}>i</span>
              <span style={{ color: "#e520ff" }}>f</span>
              <span style={{ color: "#a621ff" }}>t</span>
              <span style={{ color: "#ffb516" }}>s</span>
            </b>
          </h1>
    {/* <div><strong>บริษัท เบต้าชิฟ จำกัด</strong></div> */}
    <div>2JR7+JPJ ตำบล คลองหนึ่ง อำเภอคลองหลวง ปทุมธานี 12120</div>
  </div>

  <div className="footer-section">
    <div><strong>ติดต่อเรา</strong></div>
    <div>Facebook: <a style={{
      color: "black",
      textDecoration: "none",
    }} href="https://www.facebook.com/profile.php?id=100087575394420" >Betashifts</a></div>
    <div>Discord: <a style={{
      color: "black",
      textDecoration: "none",
    }} href="https://discord.gg/HUDn3aYGjc" >discord.gg/HUDn3aYGjc</a></div>
  </div>

  <div className="footer-section services">
    <div><strong>บริการของเรา</strong></div>
    <div><img style={{
      borderRadius: "5px",
    }} src="https://img5.pic.in.th/file/secure-sv1/kawaii77aef6f798f28865.png" alt="" height={30} /> คอร์กี้บริการปล่อยเช่าเว็บ</div>
  </div>
</div>
<hr />
<div className="bottom">
© 2025 Betashifts. All rights reserved.
</div>
    </div>/*ห้ามยุ่ง*/
  );
};

export default Home;